=== asclepias/asclepias-schema/jsonschema/event.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://asclepias.org/schema/event-v1.0.json",
    "title": "Event message schema.",
    "description": "Schema of the event message.",
    "additionalProperties": false,
    "type": "object",
    "properties": {
        "event_type": {
            "type": "string",
            "description": "Type of the event. Controlled vocabulary: 'relation_created' or 'relation_deleted'",
            "enum": ["relation_created", "relation_deleted"]

        },
        "creator": {
            "type": "string",
            "description": "High-level name of the part which emmited this event."
        },
        "source": {
            "type": "string",
            "description": "Name of the source, algorithm or procedure, which created this event."
        },
        "payload": {
            "type": "array",
            "description": "Payload information specific to the event_type. An array, containing one or more payloads of the structure matching with the event_type.",
            "items": {
                "anyOf": [
                    {
                        "$ref": "https://asclepias.org/schema/relation-v1.0.json"
                    }
                ]
            }
        },
        "id": {
            "type": "string",
            "description": "Globally unique identifier of the event (UUID version 4 as specified in RFC 4122)."
        },
        "time": {
            "type": "string",
            "description": "Time when the payload information was created."
        }
    },
    "required": [
      "event_type",
      "creator",
      "source",
      "payload",
      "id",
      "time"
    ]
}

=== asclepias/asclepias-schema/examples/zenodo-v1/data/simple/simple-1-relation_created.json
{
    "event_type": "relation_created",
    "creator": "Zenodo",
    "id": "35c82ba8-589c-4af1-9752-cf3ab15895da",
    "source": "Zenodo",
    "time": "1507842551.13",
    "payload": [
        {
            "relationship_type": {
                "original_relationship_schema": "DataCite",
                "original_relationship_name": "IsIdenticalTo",
                "scholix_relationship": "IsRelatedTo"
            },
            "relation_provider": {
                "name": "Zenodo"
            },
            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
            "target": {
                "identifier": {
                    "id_schema": "URL",
                    "id": "https://zenodo.org/record/11"
                }
            },
            "source": {
                "publisher": {
                    "name": "Zenodo"
                },
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.11"
                },
                "type": {
                    "name": "literature",
                    "sub_type_schema": "https://zenodo.org/schemas/records/record-v1.0.0.json#/resource_type/subtype",
                    "sub_type": "publication-article"
                },
                "publication_date": "2017-10-12"
            }
        },
        {
            "relationship_type": {
                "original_relationship_schema": "DataCite",
                "original_relationship_name": "IsPartOf",
                "scholix_relationship": "IsRelatedTo"
            },
            "relation_provider": {
                "name": "Zenodo"
            },
            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
            "target": {
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.10"
                }
            },
            "source": {
                "publisher": {
                    "name": "Zenodo"
                },
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.11"
                },
                "type": {
                    "name": "literature",
                    "sub_type_schema": "https://zenodo.org/schemas/records/record-v1.0.0.json#/resource_type/subtype",
                    "sub_type": "publication-article"
                },
                "publication_date": "2017-10-12"
            }
        },
        {
            "relationship_type": {
                "original_relationship_schema": "DataCite",
                "original_relationship_name": "Cites",
                "scholix_relationship": "References"
            },
            "relation_provider": {
                "name": "Zenodo"
            },
            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
            "target": {
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.53155"
                }
            },
            "source": {
                "publisher": {
                    "name": "Zenodo"
                },
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.11"
                },
                "type": {
                    "name": "literature",
                    "sub_type_schema": "https://zenodo.org/schemas/records/record-v1.0.0.json#/resource_type/subtype",
                    "sub_type": "publication-article"
                },
                "publication_date": "2017-10-12"
            }
        },
        {
            "relationship_type": {
                "original_relationship_schema": "DataCite",
                "original_relationship_name": "Cites",
                "scholix_relationship": "References"
            },
            "relation_provider": {
                "name": "Zenodo"
            },
            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
            "target": {
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.56799"
                }
            },
            "source": {
                "publisher": {
                    "name": "Zenodo"
                },
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.11"
                },
                "type": {
                    "name": "literature",
                    "sub_type_schema": "https://zenodo.org/schemas/records/record-v1.0.0.json#/resource_type/subtype",
                    "sub_type": "publication-article"
                },
                "publication_date": "2017-10-12"
            }
        }
    ]
}

=== asclepias/asclepias-schema/examples/zenodo-v1/data/simple/simple-3-relation_deleted.json
{
    "event_type": "relation_deleted",
    "creator": "Zenodo",
    "id": "03e942d7-966d-4f11-9181-f2f1bde1f002",
    "source": "Zenodo",
    "time": "1507843778.39",
    "payload": [
        {
            "relationship_type": {
                "original_relationship_schema": "DataCite",
                "original_relationship_name": "Cites",
                "scholix_relationship": "References"
            },
            "relation_provider": {
                "name": "Zenodo"
            },
            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
            "target": {
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.53155"
                }
            },
            "source": {
                "publisher": {
                    "name": "Zenodo"
                },
                "identifier": {
                    "id_schema": "DOI",
                    "id_url": "https://doi.org",
                    "id": "10.5072/zenodo.11"
                },
                "type": {
                    "name": "literature",
                    "sub_type_schema": "https://zenodo.org/schemas/records/record-v1.0.0.json#/resource_type/subtype",
                    "sub_type": "publication-article"
                },
                "publication_date": "2017-10-12"
            }
        }
]
}
